trash_collector/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
]

trash_collector/customers/urls.py
from django.urls import path
from . import views


app_name = "customers"
urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name="create"),
    path('editsuspensiondates/', views.suspension, name="suspension"),
    path('myaccount/', views.my_account, name="my_account"),
    path('changepickupdate/', views.pickup_day, name="pickup_day"),
    path('specialpickup/', views.special_pickup_date, name="special_pickup_date"),
]

trash_collector/employees/urls.py
from django.urls import path
from . import views

app_name = "employees"
urlpatterns = [
    path('', views.index, name="index"),
    path("create/", views.create, name="create"),
    path("register_pickup/", views.register_pickup, name="register_pickup"),
    path("search_completed_pickups/", views.search_completed_pickups,
         name="search_completed_pickups"),
    path("customers_by_day/", views.customers_by_day, name="customers_by_day"),
    path("customer_detail/<int:customer_id>/",
         views.customer_detail, name="customer_detail")
]

trash_collector/trash_collector/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # First adding our custom routes from our accounts app's urls.py (for our custom registration)
    path('accounts/', include('accounts.urls')),
    # Then adding django's built in routes (login and logout). Notice there is no login function in accounts/views.py
    path('accounts/', include('django.contrib.auth.urls')),
    # Adding all urls from customer app
    path('customers/', include('customers.urls')),
    # Adding all urls from employees app
    path('employees/', include('employees.urls')),
    # 'home' redirects a user to the appropriate index based on their auth group. Investigate views.py for more info
    path('', views.group_redirect, name='home')
]

trash_collector/templates/base.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>{% block title %}{% endblock %}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"
    integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js"
    integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/"
    crossorigin="anonymous"></script>
</head>

<body>
  {% if user.is_authenticated %}
  {% for group in user.groups.all%}
  {% if group.name == "Customers" %}
  {% include 'customer_navbar.html' %}

  {% elif group.name == "Employees" %}
  {% include 'employee_navbar.html' %}

  {% endif %}
  {% endfor %}
  {% endif %}
  <main>
    <h1>{% block header %} {% endblock %}</h1>
    {% block content %}
    {% endblock %}
  </main>
</body>

</html>
{# This is the parent template that should be extended by any other view you create #}
{# Todo: Add navbar links, link to stylesheets, style layout #}

trash_collector/templates/customer_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand">Customer</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'customers:index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'customers:pickup_day' %}">Change Pickup</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'customers:suspension' %}">Suspend Account</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'customers:special_pickup_date' %}">1-Time Pickup</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'customers:my_account' %}">Account Info</a>
                </li>
            </ul>
            <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
        </div>
    </div>
</nav>

trash_collector/templates/employee_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand">Employee</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'employees:index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'employees:create' %}">Create Employee</a>
                </li>

            </ul>
            <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
        </div>
    </div>
</nav>

trash_collector/templates/home.html
{% extends 'base.html' %}

{% block title %} Trash Collector {% endblock %}

{% block header %} <center>Trash Collector</center> {% endblock %}

{% block content %}
<center>
  <br />
  {% if user.is_authenticated %}
  Hello {{ user.username }}. You don't have a group assigned. Please contact administrator or attempt to register again.
  <p><a href="{% url 'logout' %}">Log Out</a></p>
  {% else %}
  <p>You are not logged in. Please log in or create an account.</p>
  <a href="{% url 'login' %}" class="btn btn-primary" role="button">Log In</a>
  <a href="{% url 'accounts:register' %}" class="btn btn-secondary" role="button">Sign Up</a>
  {% endif %}
</center>
{% endblock %}

{# This is the home page that allows a logged out user to register or log in #}