trash_collector/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
]

trash_collector/employees/urls.py
from django.urls import path
from . import views

app_name = "employees"
urlpatterns = [
    path('', views.index, name="index"),
    path("create/", views.create, name="create"),
    path("register_pickup/", views.register_pickup, name="register_pickup"),
    path("search_completed_pickups/", views.search_completed_pickups,
         name="search_completed_pickups"),
    path("customers_by_day/", views.customers_by_day, name="customers_by_day"),
    path("customer_detail/<int:customer_id>/",
         views.customer_detail, name="customer_detail")
]

trash_collector/trash_collector/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # First adding our custom routes from our accounts app's urls.py (for our custom registration)
    path('accounts/', include('accounts.urls')),
    # Then adding django's built in routes (login and logout). Notice there is no login function in accounts/views.py
    path('accounts/', include('django.contrib.auth.urls')),
    # Adding all urls from customer app
    path('customers/', include('customers.urls')),
    # Adding all urls from employees app
    path('employees/', include('employees.urls')),
    # 'home' redirects a user to the appropriate index based on their auth group. Investigate views.py for more info
    path('', views.group_redirect, name='home')
]

trash_collector/employees/models.py
from django.db import models

# Create your models here.

# TODO: Create an Employee model with properties required by the user stories


class Employee(models.Model):
    name = models.CharField(max_length=50)
    zipcode = models.CharField(max_length=5)
    user = models.ForeignKey('accounts.User', blank=True,
                             null=True, on_delete=models.CASCADE)

trash_collector/employees/views.py
from django.http.response import HttpResponseRedirect
from customers.models import Customer, CompletedPickup, Special_pickups
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from django.apps import apps
from .models import Employee
import datetime


def index(request):
    Customer = apps.get_model('customers', 'Customer')
    Special_pickups = apps.get_model('customers', 'Special_pickups')

    current_user = request.user

    try:
        current_employee = Employee.objects.get(user=current_user)
    except:
        return create(request)

    todays_customers = get_todays_customers(current_employee)

    context = {
        'user': current_user,
        'todays_customers': todays_customers,
        'current_employee': current_employee,

    }

    return render(request, 'employees/index.html', context)


def create(request):
    if request.method == "POST":
        name = request.POST.get("name")
        user = request.user
        zipcode = request.POST.get("zipcode")
        if len(zipcode) == 5 and zipcode.isnumeric():
            new_employee = Employee(name=name, user=user, zipcode=zipcode)
            new_employee.save()
            return index(request)
        else:
            return render(request, 'employees/create.html')
    else:
        return render(request, 'employees/create.html')


def register_pickup(request):
    Customer = apps.get_model('customers', 'Customer')
    CompletedPickup = apps.get_model('customers', 'CompletedPickup')

    current_user = request.user
    current_employee = Employee.objects.get(user=current_user)

    customers = get_todays_customers(current_employee)

    if request.method == "POST":
        selected_customer_ids = request.POST.getlist("customer_checks")
        today = datetime.date.today()

        for customer_id in selected_customer_ids:
            current_customer = Customer.objects.get(id=customer_id)
            current_pickup = CompletedPickup(
                date=today, customer=current_customer, employee=current_employee)
            current_pickup.save()
            charge_customer(current_customer)

        return HttpResponseRedirect(reverse("employees:index"))
    else:
        eligible_customers = get_eligible_pickup_customers(customers)

        context = {
            "user": current_user,
            "eligible_customers": eligible_customers
        }
        return render(request, 'employees/register_pickup.html', context)


def search_completed_pickups(request):
    current_user = request.user
    current_employee = Employee.objects.get(user_id=current_user.pk)
    matched_customers = Customer.objects.filter(
        zipcode=current_employee.zipcode)

    if request.method == "POST":
        filter_date = request.POST.get("filter_date")
        filter_customer_id = request.POST.get("filter_customer")
        if filter_customer_id:
            filter_customer = Customer.objects.get(id=filter_customer_id)
        else:
            filter_customer = None
    else:
        filter_date = None
        filter_customer = None

    filtered_results = pickup_search_results(
        current_employee, filter_date, filter_customer)
    context = {
        "search_results": filtered_results[0],
        "user": current_user,
        "matched_customers": matched_customers,
        "search_results_string": filtered_results[1],
    }
    return render(request, 'employees/search_completed_pickups.html', context)


def customers_by_day(request):
    current_user = request.user
    current_employee = Employee.objects.get(user_id=current_user.pk)
    matched_customers = Customer.objects.filter(
        zipcode=current_employee.zipcode)

    filter_date = None
    if request.method == "POST":
        filter_date = request.POST.get("filter_date")

    if not filter_date:
        filter_date = "Monday"

    matched_customers = get_customers_by_pickup_day(
        current_employee, filter_date)

    context = {
        "user": current_user,
        "matched_customers": matched_customers,
        "selected_day": filter_date,
    }

    return render(request, 'employees/customers_by_day.html', context)


def customer_detail(request, customer_id):
    customer = Customer.objects.get(id=customer_id)

    additional_pickups = Special_pickups.objects.filter(customer_id=customer)

    context = {
        "customer": customer,

        "additional_pickups": additional_pickups
    }

    return render(request, f'employees/customer_detail.html', context)


def get_customers_by_pickup_day(employee, weekday):
    return Customer.objects.filter(pickup_day=weekday).filter(zipcode=employee.zipcode)


def pickup_search_results(employee, date, customer):
    if date and customer:
        filtered_pickups = CompletedPickup.objects.filter(employee_id=employee.pk).filter(
            date=date).filter(customer_id=customer.pk).order_by('date')
        filtered_pickup_string = f'Search results for {customer.name} on {date}'
    elif date:
        filtered_pickups = CompletedPickup.objects.filter(
            employee_id=employee.pk).filter(date=date).order_by('date')
        filtered_pickup_string = f'Search results for {date}'
    elif customer:
        filtered_pickups = CompletedPickup.objects.filter(
            employee_id=employee.pk).filter(customer_id=customer.pk).order_by('customer_id')
        filtered_pickup_string = f'Search results for {customer.name}'
    else:
        filtered_pickups = CompletedPickup.objects.filter(
            employee_id=employee.pk)
        filtered_pickup_string = 'All pickups'
    return (filtered_pickups, filtered_pickup_string)


def charge_customer(customer):
    customer.balance += 5
    customer.save()


def get_eligible_pickup_customers(todays_customers):
    today = datetime.date.today()
    eligible_pickup_customers = []
    CompletedPickup = apps.get_model('customers', 'CompletedPickup')

    todays_completed_pickups = CompletedPickup.objects.filter(date=today)
    ineligible_ids = [
        pickup.customer_id for pickup in todays_completed_pickups]

    eligible_pickup_customers = [
        customer for customer in todays_customers if customer.id not in ineligible_ids]

    return eligible_pickup_customers


def get_todays_customers(current_employee):
    Special_pickups = apps.get_model('customers', 'Special_pickups')
    todays_customers = []

    today = datetime.date.today()
    weekday = get_weekday_string(today)

    zip_and_day_match_customers = Customer.objects.filter(
        zipcode=current_employee.zipcode).filter(pickup_day=weekday)
    todays_customers = get_only_active_customers(
        zip_and_day_match_customers, today)

    todays_special_pickups = Special_pickups.objects.filter(
        special_pickup_date=today)
    special_pickup_customers = []
    for pickup in todays_special_pickups:
        pickup_customer = Customer.objects.filter(id=pickup.customer_id)
        for customer in pickup_customer:
            if customer.zipcode == current_employee.zipcode:
                special_pickup_customers.append(customer)
    active_special_pickup_customers = get_only_active_customers(
        special_pickup_customers, today)

    todays_customers = merge_unique_customers(
        todays_customers, active_special_pickup_customers)

    return todays_customers


def get_weekday_string(day):
    day_num = day.weekday()

    weekdays = {
        0: "Monday",
        1: "Tuesday",
        2: "Wednesday",
        3: "Thursday",
        4: "Friday",
        5: "Saturday",
        6: "Sunday"
    }

    return weekdays[day_num]


def get_only_active_customers(customers, today):
    active_customers = []
    for customer in customers:
        suspend_start = customer.suspend_start
        suspend_end = customer.suspend_end
        if (suspend_start and suspend_end) and (not (customer.suspend_start <= today and customer.suspend_end >= today)):
            active_customers.append(customer)
        elif not (suspend_end and suspend_start):
            active_customers.append(customer)

    return active_customers


def merge_unique_customers(customers1, customers2):
    unique_customers = []

    for customer in customers1:
        if customer not in unique_customers:
            unique_customers.append(customer)
    for customer in customers2:
        if customer not in unique_customers:
            unique_customers.append(customer)

    return unique_customers

trash_collector/employees/templates/employees/create.html
{% extends 'base.html' %}

{% block title %} Create Employee {% endblock %}
{% block header%} <center>Create Employee</center> {% endblock %}

{% block content %}
{% if user.is_authenticated %}
<div class="container col-6">
    <form method="POST" action="{% url 'employees:create' %}">
        {% csrf_token %}
        <div class="input-group mb-3">
            <span class="input-group-text" id="basic-addon2">Full Name</span>
            <input type="text" class="form-control" placeholder="name" aria-label="name" name="name" id="name">
        </div>

        <div class="input-group mb-3">
            <span class="input-group-text" id="basic-addon2">5 digit Zipcode</span>
            <input type="text" class="form-control" placeholder="zipcode" aria-label="zipcode" name="zipcode"
                id="zipcode">
        </div>

        <div class="input-group mb-3">
            <input type="submit" value="Submit Info" class="btn btn-primary">
        </div>
    </form>
</div>
{% else %}
<center>
    <p>You are not logged in. Please log in or create an account.</p>
    <a href="{% url 'login' %}" class="btn btn-primary" role="button">Log In</a>
    <a href="{% url 'accounts:register' %}" class="btn btn-secondary" role="button">Sign Up</a>
</center>
{% endif %}



{% endblock %}

trash_collector/employees/templates/employees/customer_detail.html
{% extends 'base.html' %}
{# This top line allows this template to utilizing the styling and layout from the base. All your templates should do the same. #}

{% block title %} Customer Detail Page {% endblock %}

{% block header %} {{ customer.name }}'s Account Details  {% endblock %}

{% block content %}
  <!-- Go here if customer logged in -->
  {% if user.is_authenticated %}

    <h3 class="col-sm-6 mb-4 bg-warning p-2 rounded text-center">Current Balance:  ${{ customer.balance }}</h3>

    <ul class="list-group list-group-flush rounded mb-4">
        <li class="list-group-item col-sm-6 p-3 bg-info border border-light text-dark">

            <label class="fw-bold">
                Name:
            </label> {{ customer.name}}<br>

            <label class="fw-bold">
                Address: 
            </label> {{customer.address}}, {{customer.zipcode}}<br>

            <label class="fw-bold">
                Weekly Pickup Day:
            </label> {{ customer.pickup_day }}<br>

                <label class="fw-bold">
                    Special Pickup Date(s):
            </label> {{customer.special_pickup_date}}
                {% for pickup in additional_pickups %}
                    {{ pickup.special_pickup_date }} <br>
                {% endfor %}
            <br>
            <label class="fw-bold text-success">
                Suspension Start:
            </label> {{customer.suspend_start}}<br>

            <label class="fw-bold text-danger">
                Suspension End:
            </label> {{customer.suspend_end}}
        </li>
    </ul>
    
    <iframe class="col-sm-6 mb-4 embed-responsive embed-responsive-1by1" title="customer_addres_map" src="{{api_url}}" allowfullscreen></iframe>
    <br>

    <button class="btn btn-primary"><a href="{% url 'employees:index' %}"  class="text-uppercase text-decoration-none text-light">Back</a></button>

  <!-- If user not logged in -->
  {% else %}
    <p>You are at the customer index, but you are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  {% endif %}
{% endblock %}

trash_collector/employees/templates/employees/customers_by_day.html
{% extends 'base.html' %}

{% block title %} Search by Day {% endblock %}

{% block header %} Search by Day {% endblock %}

{% block content %}
  {% if user.is_authenticated %}

    <form action="{% url 'employees:customers_by_day' %}" method="post" class="col-sm-6 mb-4">
        {% csrf_token %}
          <div class="input-group mb-4">
            <label for="customers_by_day" class="input-group form-control fw-bold bg-danger text-light rounded">Pickup Day:</label>
                <select class="input-group form-control dropdown" name="filter_date">
                  <option class="dropdown-item" value="none" selected disabled hidden> Select A Day </option>
                  <option class="dropdown-item" value="Monday"> "Monday"</option>
                  <option class="dropdown-item" value="Tuesday"> "Tuesday"</option>
                  <option class="dropdown-item" value="Wednesday"> "Wednesday"</option>
                  <option class="dropdown-item" value="Thursday"> "Thursday"</option>
                  <option class="dropdown-item" value="Friday"> "Friday"</option>
                  <option class="dropdown-item" value="Saturday"> "Saturday"</option>
                  <option class="dropdown-item" value="Sunday"> "Sunday"</option>
                </select>
              <button type="submit" class="input-group form-control btn btn-primary col-sm-2 text-uppercase">Search</button>
          </div>
  </form>

    <h3 class="col-sm-6 mb-4 bg-warning p-2 rounded text-center">Search Results for {{selected_day}}: </h3>

    <ul class="list-group list-group-flush rounded mb-4">
        {% for customer in matched_customers %}
          <li class="list-group-item col-sm-6 p-3 bg-info border border-light fw-bold text-dark">
            <a href="{% url 'employees:customer_detail' customer.id %}" class="text-decoration-none text-dark">
              {{customer.name}}<br>
              {{customer.address}}, {{customer.zipcode}}<br>
              Pickup Day: {{customer.pickup_day}}
            </a>
          </li>

        {% endfor %}
    </ul>

    <img class="img-fluid col-sm-6 mb-2 embed-responsive embed-responsive-1by1" alt="Map of Customers" title="customer_address_map" src="{{api_url}}" allowfullscreen></iframe>


   
  {% else %}
    <p>You are at the employee index, but you are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  {% endif %}
{% endblock %}

trash_collector/employees/templates/employees/index.html
{% extends 'base.html' %}

{% block title %} Employee Home {% endblock %}

{% block header %} Hello {{ current_employee.name }}! {% endblock %}

{% block content %}
  {% if user.is_authenticated %}

    <h3 class="col-sm-6 mb-4  p-2 text-center">Today's Customers: </h3>
        
    <ul class="list-group list-group-flush mb-4">
        {% for customer in todays_customers %}
        <li class="list-group-item col-sm-6 p-3 bg-info border border-light fw-bold text-dark">
          {{customer.name}} <br> 
          {{customer.address}}, {{customer.zipcode}}
        </li>
        {% endfor %}
    </ul>
    <button type="button" class="col-sm-6 btn btn-dark mb-2">
      <a class="text-light text-uppercase text-decoration-none" href="{% url 'employees:register_pickup' %}">Register New Pickups</a>
    </button>

    <br>

    <button type="button" class="col-sm-6 btn btn-dark mb-4">
      <a class="text-light text-uppercase text-decoration-none" href="{% url 'employees:search_completed_pickups' %}">Search Completed Pickups</a>
    </button>

  

  {% else %}
    <p>You are at the employee index, but you are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  {% endif %}
{% endblock %}

trash_collector/employees/templates/employees/register_pickup.html
{% extends 'base.html' %}

{% block title %}{% block header %} Register New Pickups {% endblock %}{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
    
    <h3 class="col-sm-6 mb-2 bg-warning p-2 text-center rounded">Eligible Customers: </h4>

    <form action="{% url 'employees:register_pickup' %}" method="post" class="rounded col-sm-6 mb-2">
        {% csrf_token %}
        <div class="list-group list-group-flush mb-2 rounded fw-bold text-dark">
            {% for customer in eligible_customers %}
            <label class="list-group-item bg-info p-3 border border-light">
                <input class="form-check-input" type="checkbox" value="{{customer.pk}}" name="customer_checks">
                {{customer.name}}<br>
                {{customer.address}}, {{customer.zipcode}}<br>
                Pickup Day:  {{customer.pickup_day}}
            </label>
            {% endfor %}
        </div>
        <button type="submit" class="btn btn-primary text-uppercase">Submit</button>
    </form>
  {% else %}
    <p>You are at the employee index, but you are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  {% endif %}
{% endblock %}

trash_collector/employees/templates/employees/search_completed_pickups.html
{% extends 'base.html' %}

{% block title %}{% block header %} Search Completed Pickups {% endblock %}{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
      <form action="{% url 'employees:search_completed_pickups' %}" method="post" class="col-sm-6 mb-4">
          {% csrf_token %}
          <div class="input-group">
              <input class="input-group-text form-control" type="date" name="filter_date"></input>
              
              <select class="input-group-text form-control dropdown" name="filter_customer">
                <option class="dropdown-item" value="none" selected disabled hidden> Select Customer </option>
                {% for customer in matched_customers %}
                <option class="dropdown-item" value="{{customer.pk}}"> {{customer.name}} {{customer.address}}</option>
                {% endfor %}
              </select>
              
              <button type="submit" class="form-control btn btn-primary col-sm-2 text-uppercase">Search</button>
          </div>        
      </form>

    
        <h3 class="col-sm-6 mb-4 bg-warning p-2 rounded text-center">{{search_results_string}}: </h3> 
        </ul>

        <ul class="list-group list-group-flush rounded mb-4">
              {% for pickup in search_results %}
              <li class="list-group-item col-sm-6 p-3 bg-info border border-light fw-bold text-dark">
                  {{pickup.customer.name}}<br>
                  {{pickup.customer.address}}<br>
                  {{pickup.date}}</li>  
              {% endfor %}
          </ul>
  {% else %}
    <p>You are at the employee index, but you are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  {% endif %}
{% endblock %}