trash_collector/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
]

trash_collector/customers/urls.py
from django.urls import path
from . import views


app_name = "customers"
urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name="create"),
    path('editsuspensiondates/', views.suspension, name="suspension"),
    path('myaccount/', views.my_account, name="my_account"),
    path('changepickupdate/', views.pickup_day, name="pickup_day"),
    path('specialpickup/', views.special_pickup_date, name="special_pickup_date"),
]

trash_collector/trash_collector/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # First adding our custom routes from our accounts app's urls.py (for our custom registration)
    path('accounts/', include('accounts.urls')),
    # Then adding django's built in routes (login and logout). Notice there is no login function in accounts/views.py
    path('accounts/', include('django.contrib.auth.urls')),
    # Adding all urls from customer app
    path('customers/', include('customers.urls')),
    # Adding all urls from employees app
    path('employees/', include('employees.urls')),
    # 'home' redirects a user to the appropriate index based on their auth group. Investigate views.py for more info
    path('', views.group_redirect, name='home')
]

trash_collector/customers/models.py
from django.db import models
from django.db.models.deletion import PROTECT
from django.db.models.fields import CharField


class Customer(models.Model):
    name = models.CharField(max_length=50)
    user = models.ForeignKey('accounts.User', blank=True,
                             null=True, on_delete=models.CASCADE)
    zipcode = models.CharField(max_length=200, blank=True, null=True,)
    pickup_day = models.CharField(max_length=9, default='Monday')
    address = models.CharField(max_length=50, default='', blank=True)
    suspend_start = models.DateField(null=True, editable=True, blank=True)
    suspend_end = models.DateField(null=True, editable=True, blank=True)
    balance = models.IntegerField(default=0, blank=True)


class CompletedPickup(models.Model):
    date = models.DateField(null=False, blank=False, editable=False)
    customer = models.ForeignKey(
        'customers.Customer', blank=True, null=False, on_delete=PROTECT)
    employee = models.ForeignKey(
        'employees.Employee', blank=True, null=False, on_delete=PROTECT)


class Special_pickups(models.Model):
    special_pickup_date = models.DateField(
        null=False, blank=False, editable=False)
    customer = models.ForeignKey(
        'customers.Customer', blank=True, null=False, on_delete=PROTECT)

trash_collector/customers/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from .models import Customer, Special_pickups


def index(request):
    user = request.user
    context = {
        'user': user
    }

    try:
        logged_in_customer = Customer.objects.get(user=user)
        context['logged_in_customer'] = logged_in_customer
    except:
        return create(request)

    return render(request, 'customers/index.html', context)


def create(request):
    if request.method == "POST":
        name = request.POST.get("name")
        user = request.user
        zipcode = request.POST.get("zipcode")
        pickup_day = request.POST.get("pickup_day")
        address = request.POST.get("address")
        suspend_start = request.POST.get('suspend_start')
        suspend_end = request.POST.get('suspend_end')
        balance = 0
        if zipcode == 5:
            new_customer = Customer(name=name, user=user, zipcode=zipcode, pickup_day=pickup_day,
                                    address=address, suspend_start=suspend_start, suspend_end=suspend_end, balance=balance)
            new_customer.save()
            return index(request)
        else:
            return render(request, 'customers/create.html')
    else:
        return render(request, 'customers/create.html')


def suspension(request):
    user = request.user
    context = {
        'user': user
    }
    logged_in_customer = Customer.objects.get(user=user)
    context['logged_in_customer'] = logged_in_customer

    if request.method == "POST":
        suspend_start = request.POST.get("suspend_start")
        suspend_end = request.POST.get("suspend_end")
        if suspend_start and suspend_end:
            if suspend_end < suspend_start:
                temp = suspend_end
                suspend_end = suspend_start
                suspend_start = temp

            logged_in_customer.suspend_start = suspend_start
            logged_in_customer.suspend_end = suspend_end
            logged_in_customer.save()
            return my_account(request)
        else:
            return render(request, 'customers/suspension.html')
    else:
        return render(request, 'customers/suspension.html')


def pickup_day(request):
    user = request.user
    context = {
        'user': user
    }

    logged_in_customer = Customer.objects.get(user=user)
    context['logged_in_customer'] = logged_in_customer

    if request.method == "POST":
        pickup_day = request.POST.get("pickup_day")

        if pickup_day:
            logged_in_customer.pickup_day = pickup_day
            logged_in_customer.save()

        return my_account(request)

    else:
        return render(request, 'customers/pickup_day.html')


def my_account(request):
    user = request.user
    context = {
        'user': user
    }

    logged_in_customer = Customer.objects.get(user=user)
    context['logged_in_customer'] = logged_in_customer

    all_special_dates = get_all_special_pickup_dates(request)
    context['all_special_dates'] = all_special_dates

    return render(request, 'customers/my_account.html', context)


def special_pickup_date(request):
    user = request.user
    context = {
        'user': user
    }

    logged_in_customer = Customer.objects.get(user=user)
    context['logged_in_customer'] = logged_in_customer

    if request.method == "POST":
        special_pickup_date = request.POST.get("special_pickup_date")
        customer = logged_in_customer

        if special_pickup_date:
            new_special_pickup = Special_pickups(
                special_pickup_date=special_pickup_date, customer=customer)
            new_special_pickup.save()

        return my_account(request)

    else:
        return render(request, 'customers/specialpickupdate.html')


def get_all_special_pickup_dates(request):
    all_special_dates = Special_pickups.objects.all()

    return all_special_dates

trash_collector/customers/templates/customers/create.html
{% extends 'base.html' %}
{# This top line allows this template to utilizing the styling and layout from the base. All your templates should do the same. #}

{% block title %} Create Account {% endblock %}

{% block header %} Please enter your account info: {% endblock %}

{% block content %}

    <!-- Go here if customer logged in -->
    {% if user.is_authenticated %}
      <form action="{% url 'customers:create' %}" method="post" class="col-sm-6">
          {% csrf_token %}
          <div class="input-group">
            <input type="text" class="form-control" id="name" placeholder="First and Last Name">
        </div>
            <div class="input-group">
                <input type="text" class="form-control" id="address" placeholder="Address">
          </div>
          <div class="input-group">
            <input type="text" class="form-control" id="zipcode" placeholder="Zipcode">
        </div>
          <div class="input-group">
            <input type="text" class="form-control" id="pickup_day" placeholder="Enter preferred pickup day">
          </div>
          <button class="form-control btn btn-primary text-uppercase btn-sm mt-2" type="submit">Create</button>
      </form>
  <!-- If user not logged in -->
  {% else %}
  <div class="container-fluid m-3">
    <p>You are at the customer index, but you are not logged in.</p>
        <a class="btn btn-primary text-uppercase" href="{% url 'login' %}">Log In</a>
        <a class="btn btn-primary text-uppercase" href="{% url 'accounts:register' %}">Sign Up</a>
    </div>
  {% endif %}
{% endblock %}

trash_collector/customers/templates/customers/index.html
{% extends 'base.html' %}
{# This top line allows this template to utilizing the styling and layout from the base. All your templates should do
the same. #}

{% block title %} Customer Home {% endblock %}

{% block header %} {% endblock %}

{% block content %}
{% if user.is_authenticated %}
<div class="container">
  <h1>Hello {{ user.username }}!</h1>
  <h2>Your current pick up date is: {{ logged_in_customer.reg_pickup }} </h2>
</div>

{% else %}
<p>You are at the customer index, but you are not logged in.</p>
<a href="{% url 'login' %}">Log In</a>
<a href="{% url 'accounts:register' %}">Sign Up</a>
{% endif %}
{% endblock %}

trash_collector/customers/templates/customers/my_account.html
{% extends 'base.html' %}
{# This top line allows this template to utilizing the styling and layout from the base. All your templates should do the same. #}

{% block title %} Customer Account Page {% endblock %}

{% block header %} {{ logged_in_customer.name }}'s Account Details  {% endblock %}

{% block content %}
  <!-- Go here if customer logged in -->
  {% if user.is_authenticated %}

    <h3 class="col-sm-6 mb-4 bg-warning p-2 rounded text-center">Your Current Balance is:  ${{ logged_in_customer.balance }}</h3>


    <ul class="list-group list-group-flush rounded mb-4">
      <li class="list-group-item col-sm-6 p-3 border border-light text-dark">

          <label class="fw-bold">
            Name:
          </label> {{ logged_in_customer.name}}<br>

          <label class="fw-bold">
            Address: 
          </label> {{logged_in_customer.address}}, {{customer.zipcode}}<br>

          <label class="fw-bold">
            Weekly Pickup Day:
          </label> {{ logged_in_customer.pickup_day }}<br>

          <label class="fw-bold">
            Special Pickup Date(s):
          </label><br>
              {% for special_date in all_special_dates %}
                {% if special_date.customer == logged_in_customer %}
                  {{ special_date.special_pickup_date }}<br>
                {% endif %}
              {% endfor %}<br>

          <label class="fw-bold text-success">
              Suspension Start:
          </label> {{logged_in_customer.suspend_start}}<br>

          <label class="fw-bold text-danger">
              Suspension End:
          </label> {{logged_in_customer.suspend_end}}
      </li>
  </ul>

  
    <button class="btn btn-danger"><a href="{% url 'customers:special_pickup_date' %}"  class="ext-uppercase text-decoration-none text-light text-uppercase">Add Special Pickup</a></button>


    <button class="btn btn-primary"><a href="{% url 'customers:index' %}"  class="text-uppercase text-decoration-none text-light">Back</a>


  <!-- If user not logged in -->
  {% else %}
    <p>You are at the customer index, but you are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  {% endif %}
{% endblock %}

trash_collector/customers/templates/customers/pickup_day.html
{% extends 'base.html' %}
{# This top line allows this template to utilizing the styling and layout from the base. All your templates should do the same. #}

{% block title %} Change Pickup Day {% endblock %}

{% block header %} Select a New Pickup Day {% endblock %}

{% block content %}
  <!-- Go here if customer logged in -->
  {% if user.is_authenticated %}

    <!-- form to change Pickup Day -->
    <form action="{% url 'customers:pickup_day' %}" method="post" class="col-sm-6 mb-4">
        {% csrf_token %}
          <div class="input-group mb-4">
          <label for="pickup_day" class="input-group-text" id="basic-addon2">Pickup Day:</label>
                <select name="pickup_day" class="input-group form-control dropdown">
                  <option class="dropdown-item" value="none" selected disabled hidden> Select A Day </option>
                  <option class="dropdown-item" value="Monday"> "Monday"</option>
                  <option class="dropdown-item" value="Tuesday"> "Tuesday"</option>
                  <option class="dropdown-item" value="Wednesday"> "Wednesday"</option>
                  <option class="dropdown-item" value="Thursday"> "Thursday"</option>
                  <option class="dropdown-item" value="Friday"> "Friday"</option>
                  <option class="dropdown-item" value="Saturday"> "Saturday"</option>
                  <option class="dropdown-item" value="Sunday"> "Sunday"</option>
                </select>
            <button type="submit" class="input-group form-control btn btn-primary btn-sm text-uppercase">Submit</button>
          </div>

          <a href="{% url 'customers:my_account' %}"  class="btn btn-primary text-uppercase">Back</a>
    </form>
              
        <!-- submit change -->
        <br>
        
       
  
  {% endif %}
{% endblock %}

trash_collector/customers/templates/customers/specialpickupdate.html
{% extends 'base.html' %}
{# This top line allows this template to utilizing the styling and layout from the base. All your templates should do the same. #}

{% block title %} Special Pickups {% endblock %}

{% block header %} Select a Special Pickup Date {% endblock %}

{% block content %}
  <!-- Go here if customer logged in -->
  {% if user.is_authenticated %}
  <!-- Customer selects a special pick up date here -->
    <form action="{% url 'customers:special_pickup_date' %}" method="post" class="col-sm-6 mb-4">
        {% csrf_token %}
      <div class="input-group mb-4">
          <span class="input-group-text" id="basic-addon2">Select Date:</span>
          <input type="date" name="special_pickup_date" id="special_pickup_date" class="input-group form-control">

          <button type="submit" class="input-group form-control btn btn-primary text-uppercase">Submit changes</button>
      </div>

        <a href="{% url 'customers:my_account' %}"  class="btn btn-primary text-uppercase">Back</a>
    </form>
  
  {% endif %}
{% endblock %}

trash_collector/customers/templates/customers/suspension.html
{% extends 'base.html' %}
{# This top line allows this template to utilizing the styling and layout from the base. All your templates should do the same. #}

{% block title %} Pickup Suspension {% endblock %}

{% block header %} Select your suspension period {% endblock %}

{% block content %}
  <!-- Go here if customer logged in -->
  {% if user.is_authenticated %}
    <form action="{% url 'customers:suspension' %}" method="post" class="col-sm-6 mb-4">
      {% csrf_token %}
        <div class="input-group mb-4">
          <span class="input-group-text" id="basic-addon2">Start Date:</span>
          <input type="date" name="suspend_start" id="suspend_start" class="form-control">
        </div>

        <div class="input-group mb-4">
          <span class="input-group-text" id="basic-addon2">End Date:</span>
          <input type="date" name="suspend_end" id="suspend_end" class="form-control">
        </div>
      
      <button type="submit" class="btn btn-primary bg-primary text-uppercase col-sm-2">Submit</button>
    
      <a href="{% url 'customers:my_account' %}"  class="btn btn-primary text-uppercase col-sm-2">Back</a>
    </form>
  
  {% endif %}
{% endblock %}